name: Docker Image - Dev

on:
  push:
    branches: [ "dev" ]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Convert repository to lowercase
        run: |
          echo "REPO_LC=${REPO,,}" >> $GITHUB_ENV
        env:
          REPO: ${{ github.repository }}

      - name: Set Short SHA Tag
        run: |
          echo "SHORT_SHA=${FULL_SHA:0:6}" >> $GITHUB_ENV
        env:
          FULL_SHA: ${{ github.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPO_LC }}:latest
            ${{ env.REGISTRY }}/${{ env.REPO_LC }}:${{ env.SHORT_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
